name: Deploy & Notify

on:
  push:
    branches:
    - master

jobs:
  notify-slack:

    runs-on: ubuntu-latest
    
    steps:
    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: 'Deploy GitHub Pages'
        channel: '#igolopolosov-github-io-notifications'
        url: ${{ secrets.SLACK_WEBHOOK }}
        icon_emoji: github
        username: GitHub workflows
