name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: '*Deploy github pages*'
        channel: '#igolopolosov-github-io-notifications'
        url: ${{ secrets.SLACK_WEBHOOK }}
